app:
mongodb:
  url: mongodb://user:user@localhost:27017/teamlix # mongo connection string
redis:
  host: localhost # redis host
  port: 6379 # redis port
  db: 0 # redis db
  password:  # redis password